version: 2.1
orbs:
  node: circleci/node@5

jobs:
  test-node:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Run tests
          command: npm test --passWithNoTests

  deploy:
    docker:
      - image: cimg/base:stable
    steps:
      - add_ssh_keys:
          fingerprints:
            - "SHA256:7K1nZcnB5r2EY0MKi1nx1s2HmG9n7qYjkk+QXrDvTxY"
      - run:
          name: Deploy to EC2
          command: |
            ssh -o StrictHostKeyChecking=no ubuntu@<YOUR_EC2_IP> bash -c '
              cd ~/devops-simpleApp
              git reset --hard HEAD  # Discard local changes
              git pull origin main  # Pull latest changes
              npm install  # Install dependencies

              # Start the application properly (choose ONE method)
              nohup npm start > app.log 2>&1 &  # Without PM2
              # pm2 start npm --name "devops-app" -- start  # If using PM2
              # pm2 save  # Save PM2 state (only if using PM2)
            '

workflows:
  build-and-deploy:
    jobs:
      - test-node
      - deploy:
          requires:
            - test-node
