version: 2.1
orbs:
  node: circleci/node@5

jobs:
  test-node:
    # Install node dependencies and run tests
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Run tests
          command: npm test --passWithNoTests

  deploy:
    # Deploy job to automatically update EC2
    docker:
      - image: cimg/base:stable
    steps:
      - add_ssh_keys:
          fingerprints:
            - "SHA256:7K1nZcnB5r2EY0MKi1nx1s2HmG9n7qYjkk+QXrDvTxY"
      - run:
          name: Deploy to EC2
          command: |
            ssh -o StrictHostKeyChecking=no ubuntu@3.209.163.115 bash -c '
              cd ~/devops-simpleApp
              git pull origin main
              pm2 restart all  # Restart Node.js app
            '

workflows:
  build-and-deploy:
    jobs:
      - test-node
      - deploy:
          requires:
            - test-node
