version: 2.1
orbs:
  node: circleci/node@5

jobs:
  test-node:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Run tests
          command: npm test --passWithNoTests

  deploy:
    docker:
      - image: cimg/base:stable
    steps:
      - add_ssh_keys:
          fingerprints:
            - "SHA256:7K1nZcnB5r2EY0MKi1nx1s2HmG9n7qYjkk+QXrDvTxY"
      - run:
          name: Deploy to EC2
          command: |
            ssh -o StrictHostKeyChecking=no ubuntu@3.209.163.115 bash -c '
              cd ~/devops-simpleApp
              git reset --hard HEAD  # Discard local changes
              git pull origin main
              npm install -g pm2  # Ensure PM2 is installed
              npm install  # Install dependencies
              pm2 delete all || true  # Remove any old processes
              pm2 start npm --name "devops-app" -- start  # Start app using npm
              pm2 save  # Save process for auto-restart
            '

workflows:
  build-and-deploy:
    jobs:
      - test-node
      - deploy:
          requires:
            - test-node
